# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: Bernard's Blog # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  Bernard's Blog # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: nord # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: sunset # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: Home # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: Documentation
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: Examples
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: project
      text: Project
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    # - id: friend
    #   text: Friend
    #   href: /friend
    #   svg: "material-symbols:supervisor-account-outline-rounded"
    #   target: _self
    - id: contact
      text: Contact
      href: "mailto:muyun2357@outlook.com"
      target: _blank # åœ¨æ–°æ ‡ç­¾é¡µæ‰“å¼€
      svg: "material-symbols:attach-email-outline-rounded"

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: Bernard # ç”¨æˆ·å
  site: "https://bernardyan2357.github.io/" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://afdian.tv/a/muyun2357" # é“¾æ¥
        ariaLabel: Support my work # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: Support my work # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:cup-line"
      - href: "https://github.com/BernardYan2357"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://www.xiaoheihe.cn/app/user/profile"
        ariaLabel: xiaoheihe
        title: xiaoheihe
        svg: "<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M44.865 33.492c-.415-9.61-1.708-15.937-2.725-19.566c-.694-2.474-2.84-4.11-5.398-4.357C33.848 9.291 29.5 8.998 24 8.998s-9.847.293-12.74.571c-2.559.247-4.705 1.883-5.399 4.357c-1.017 3.629-2.31 9.956-2.725 19.566c-.171 3.943 2.218 7.506 6.164 7.506q.785-.002 1.473-.045c3.17-.201 5.383-2.716 6.373-5.734l.04-.117c.33-1.006 1.052-1.84 2.077-2.1c1.05-.269 2.63-.537 4.737-.537s3.688.268 4.738.536c1.025.262 1.748 1.095 2.078 2.101l.038.117c.99 3.018 3.205 5.533 6.374 5.733q.688.045 1.472.046c3.947 0 6.336-3.563 6.165-7.506M15 17v8m4-4h-8m22 3v1m-3-4h-1m4-4v1m4 3h-1"/></svg>"
      - href: "https://x.com/Neigl6"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.tv/a/muyun2357" # é“¾æ¥
        ariaLabel: Support my work # å›¾æ ‡çš„å¯è®¿é—®æ€§æ ‡ç­¾
        title: Support my work # å›¾æ ‡çš„æ‚¬æµ®æ ‡é¢˜
        svg: "ri:cup-line"
      - href: "https://github.com/BernardYan2357"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://www.xiaoheihe.cn/app/user/profile"
        ariaLabel: xiaoheihe
        title: xiaoheihe
        svg: "<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M44.865 33.492c-.415-9.61-1.708-15.937-2.725-19.566c-.694-2.474-2.84-4.11-5.398-4.357C33.848 9.291 29.5 8.998 24 8.998s-9.847.293-12.74.571c-2.559.247-4.705 1.883-5.399 4.357c-1.017 3.629-2.31 9.956-2.725 19.566c-.171 3.943 2.218 7.506 6.164 7.506q.785-.002 1.473-.045c3.17-.201 5.383-2.716 6.373-5.734l.04-.117c.33-1.006 1.052-1.84 2.077-2.1c1.05-.269 2.63-.537 4.737-.537s3.688.268 4.738.536c1.025.262 1.748 1.095 2.078 2.101l.038.117c.99 3.018 3.205 5.533 6.374 5.733q.688.045 1.472.046c3.947 0 6.336-3.563 6.165-7.506M15 17v8m4-4h-8m22 3v1m-3-4h-1m4-4v1m4 3h-1"/></svg>"
      - href: "https://x.com/Neigl6"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
